</div> <!--#page-wrapper-->

<footer class="footer">
  <div class="container">
    <div class="contact">
      <a href="mailto:info@globalreachout.org">info@globalreachout.org</a>
      <a href="https://www.facebook.com/globalreachout"><img src="<?php echo drupal_get_path('theme', 'growl_bravo'); ?>/images/facebook.png" alt="Facebook" class="social-media-icon"></a>
      <a href="https://twitter.com/globalreachout"><img src="<?php echo drupal_get_path('theme', 'growl_bravo'); ?>/images/twitter.png" alt="Twitter" class="social-media-icon"></a>
    </div>
    <div class="notices">
      <?php print render($page['footer']); ?>
    </div>
  </div>
</footer>
